quarkus.virtual-threads.enabled=true

quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASS}

quarkus.redis.hosts=redis://${CACHE_USER}:${CACHE_PASS}@${CACHE_HOST}:6379