spring:
  config:
    import:
  application:
    name: core

server:
  port: ${PORT:8080}

springdoc:
  show-actuator: true

common:
  docs:
    server-url: ${SERVER_URL}
management:
  endpoints:
    web:
      exposure:
        include: startup